a = (input('Digite algo:'))
print('Seu tipo e´:', (type(a)))
print(' ')
print('É um dígito:', a.isdigit())
print('É composto apenas por letras:', a.isalpha())
print('É composto apenas por numeros:', a.isnumeric())
print('É composto apenas por espaços', a.isspace())
print('Está captalizada:', a.istitle())
print('Está em letras mínusculas:', a.islower())
print('Está em maiusculas:', a.isupper())
print('São letras e numeros:', a.isalnum())